### ISSUE TITLE
ReferenceError: pry is not defined

### ISSUE THREAD

**Issue by zlwaterfield** [blainesch/pry.js#43] opened 2016-09-29 04:51 UTC
Throwing error that pry is not define:
```
ReferenceError: pry is not defined
  at eval (<anonymous>:4:14)
  at eval (<anonymous>:7:8)
```

Has anyone else come across this? Here is my code:

```
import pry from 'pryjs'

exports.index = (req, res) => {
  eval(pry.it)
};
```

**Comment by blainesch** [comment] 2016-09-29 05:01
This is due to how pry works. It's `eval`ing code and it expected the variable `pry` to expect in the outside scope, but in compiled code this isn't always the case. For this to work you'll need to run it in non-minified code.

A fix would be to figure out what variable it was called with, or maybe change the signature to something like `eval(pry, pry.it)` or maybe find another way all together to use pry internally?

**Comment by SamuraiT** [comment] 2016-10-10 05:03
this happened to me when I use inside of mocha
example, 
```js
import {expect} from 'chai'
import pry from 'pryjs'

describe('Example', () => {
  it('1 + 2 = 3', () => {
    eval(pry.it)  
    expect(1 + 2).to.equal(3);
  });
});
```
and 
```
mocha test
```
this returns error 

```
      return pry.open((function(input) {
             ^

ReferenceError: pry is not defined
  at Object.eval (<anonymous>:4:14)
  at eval (<anonymous>:7:8)
```

after using `eval(pry, pry.it)`, it stops throwing error but 
nothing happens then. don't know how to use pry.it inside of mocha :|

**Comment by blainesch** [comment] 2016-10-10 07:47
This is fixed in v1.0.3 or more specifically [this commit](https://github.com/blainesch/pry.js/commit/2064d9c17eabdffd84ead6601bd58ca8ba5306b7).

Can you verify this works for you?

**Comment by zlwaterfield** [comment] 2016-10-10 20:40
@blainesch testing on v1.0.3

Using `eval(pry.it)` is working! Thank you for the update!

I am facing an issue however that is it slow when typing and not all characters are being entered, it seems I need to enter them 2-3 times for it to actually type them out in the console.

**Comment by blainesch** [comment] 2016-10-11 03:24
Do you have an example I can test it on? All the ones I've made were fast.

**Comment by zlwaterfield** [comment] 2016-10-11 17:44
Sure, it is working and fast once the keys are typed, but i need to click to keys 2-3 times for it to be recognized. This is what i am testing on, simple express request.

```
import pry from 'pryjs'

// Ping
router.get('/ping', (req, res) => {
  eval(pry.it)
  res.json({ status:'UP' });
});
```

**Comment by blainesch** [comment] 2016-10-11 20:48
This could be caused by express. I'm going to close this and create a separate issue.

**Closed by blainesch** 2016-10-11 20:48 UTC
Labels: bug
